import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import { useSelector } from 'react-redux'
import { GET_TODOS } from '../actions/actions'
import { useDispatch } from 'react-redux'
import Button from '@mui/material/Button';

export default function Home() {
  const dispatch = useDispatch()

  let todos  = []
  todos = useSelector((state) => state.todos);


  
  const getData = async () => {
    const resp = await fetch('https://jsonplaceholder.typicode.com/posts')
    const data = await resp.json()
    dispatch({ type: GET_TODOS, payload: data})
  }
  
  useEffect(() => {
    getData()
    }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>

        </h1>
        <Button variant ='contained'>Contained</Button>

        {todos.map((item, index) => {
          return (<p className={`${styles.description} ''` } key={index}>
            {item.title}
          </p>)
        })
        }
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


// export const getServerSideProps = async()=>{
//   const resp =   await fetch('https://jsonplaceholder.typicode.com/todos/1')
//   const data = await resp.json()
//   if (!data) {
//     return{
//       Error:true
//     }
//   }
//   return{
//     props:{data}
//   }
// }
